# @package _global_
run_time: ${now:%H-%M-%S}
suffix_dir: ""
sweep_dir: ${save_dir}/${now:%Y-%m-%d}/${run_time}_${suffix_dir}
exp_settings: kl=${kl}_n=${n}_weights=${weights}
hydra:
  job:
    chdir: True
  run:
    dir: ${sweep_dir}
  sweep:
    dir: ${sweep_dir}
    subdir: ${exp_settings}_${hydra.job.num}
